name: counter_app

#Triggers (events)
on:
   push:

   pull_request:
    branch:
     -main

#functions (what needs to be done on events)
jobs:
  build: 
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: install Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm i
      - name: build project
        run: npm run build
      - name: Uplaod artifact in order to deploy
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./build

  deploy:
     name: deploy
     run: ubuntu-latest
     needs: build

     steps:
        - name: Download artifact
          uses: actions/upload-artifact@v2
          with:
            name: production-files
            uses: ./build

        - name : Deploy to github pages
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{secrets.GH_TOKEN}}
            publish_dir: ./build